# Generated by Django 4.0.5 on 2023-03-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': '4. Brand'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '1. Category'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '5. Product'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': '2. Sub Category'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': '3. Type'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products/categories'),
        ),
    ]
